version: '3.1'

services:
  redis:
    image: redis
    restart: on-failure
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6379:6379"

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: OneTool
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: { }